### ISSUE TITLE
Question on linear regression program execution

### ISSUE THREAD

**Issue by tariqrahiman** [anish-lakkapragada/SeaLion#4]
Question on linear regression program execution
 - When i try to execute, i see it refers to load_boston.
 - i see titanic_dataset. Should every data set be downloaded and loaded into Anaconda to run those ?
![sealion_linear_regression-q1](https://user-images.githubusercontent.com/913554/107436360-43592180-6ae2-11eb-8740-0fb21830c3f8.png)

**Comment by anish-lakkapragada** [comment]
First off thank you @tariqrahiman for opening this issue. 

None of the sklearn.datasets require any files to be there, they are all built in with sklearn. The reason why I used sklearn in the notebooks was to just load in datasets or split data fast, so that I didn't need to spend too much time on data preprocessing, etc. All of the ML algorithms are from SeaLion of course. 

For the titanic dataset, I couldn't see a way to load it in with other libraries so I just manually loaded it in the notebooks using the titanic_dataset.csv file. 

I added the .csv dataset I used into the notebooks folder to make sure other people have it.

**Comment by anish-lakkapragada** [comment]
Please give me the green light to close this issue, if there are no further questions. Thank you!

**Comment by tariqrahiman** [comment]
Can you let me know how long it will take for the first import to complete ?
I tried the samples but executing the first statement takes close to 20m and never completed. I have a fairly powerful i7 with enough memory, however, maybe i am doing something wrong. I am not able to execute the first import and move to the 2nd statement
![sealion_linear_regression-q2](https://user-images.githubusercontent.com/913554/107460333-cabb8a80-6b0c-11eb-9238-9d8392da6397.png)

**Comment by anish-lakkapragada** [comment]
I've been trying to figure out why that's happening for some people. can you please give me your python version number and sealion's release number (latest 4.0.7)? 

I think the reason that is is because SeaLion has numerous .pyx files that are trying to be compiled in the import. This only happens for the first import. These .pyx files are the Cython code that are then being compiled to .so files in the sealion/__init__.py. 

The reason why SeaLion does it this way is because the .so files are specific to the users OS so I cannot just give my .so files and expect it to work for everyone. 

I'm currently looking to make sure I have all of the dependencies listed. I don't have any fancy equipment or hardware but this took 10 - 40 seconds for the first import. I'm going to check to see the version numbers of my dependencies used too. 

Can you please tell me the version numbers of each of the libraries in requirements.txt? This will also help. You can find requirements.txt in the repo too. 

Thank you. I appreciate you bringing this up.

**Comment by anish-lakkapragada** [comment]
I think I found out why this is. It's because in the __init__.py I run setup.py which compiles all Cython .pyx code into .so files. When I run the setup.py file from the __init__.py file I make sure no warnings show to the user, so this must have covered up the error. I think that's what it is. The bug is fixed in 4.0.8. Please let me know if it works.

**Comment by tariqrahiman** [comment]
I did a clean uninstall and install using command line. However, the bug remains. I am not able to proceed. 
Is there a document to install via the git repository? I installed using anaconda prompt and the first import takes hours to complete even with sealion 4.1

![un-install](https://user-images.githubusercontent.com/913554/107687344-3c095380-6c5b-11eb-8698-1160c5d22565.png)
![install](https://user-images.githubusercontent.com/913554/107687350-3f9cda80-6c5b-11eb-8442-e4ba98c44d42.png)

**Comment by tariqrahiman** [comment]
Anish, the Python version is
**Python 3.8.3** (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by anish-lakkapragada** [comment]
I opened up another issue that may lead to this happening. You can see that issue over here : https://github.com/anish-lakkapragada/SeaLion/issues/5

basically SeaLion generates files that are specific to your OS in the first run. These files when you do "pip uninstall" weren't there when you got them, so they don't get deleted. This means a reinstallment for a new update will still have those old generated files. 

I know this is very annoying and I thank you for your patience. Could you please go into the directory where you have the site-packages, delete any files to do with SeaLion (the SeaLion folder and sealion-4.1.dist-info) and then reinstall 4.1. Then you can try again. 

I'm still figuring out why this would happen. You said the first import took hours to complete, does that mean that is has been completed? 

There's a while loop in the __init__ file for a user to wait while generated files are being made. In fact if you have time you can look into the __init__.py file and see how the init works. You can also add print statements throughout the code to see where it is taking the longest time. I know this is a hassle, but it may help. I'm currently trying my best to see why this could possibly happen. 

Another thing to note is that there's also a cython_ran.pickle file that will be generated if all Cython files have ran. If you call "import sealion" again it will check to see if that file exists. If that file exists, but one of the files has not been generated, it will assume that that file that hasn't been generated exists, and it will run itself through that while loop. This will mean it could go on and on, I may have missed a break statement so I will check that.

**Comment by anish-lakkapragada** [comment]
Please let me know if I was unclear about anything I just said. I may also rerelease to 4.1.1 and from now on I think its best to just delete the existing two directories and then reinstall.

**Comment by tariqrahiman** [comment]
Anish,
i deleted the 2 folders. However when I do pip install sealion it points to seaborn. Weird
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] 
Access is denied: 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\seaborn\\algorithms.py'
Consider using the `--user` option or check the permissions.

**Comment by tariqrahiman** [comment]
i used pip install --user sealion and it worked and i have the latest source. Let me try and will let you know regarding the import.
And import never completed. I closed the machine

**Comment by tariqrahiman** [comment]
Issue is resolved. Able to compile the programs. I will take a look at it. Thanks for the support
Do you have a website with documentations ?

~ Tariq Rahiman
tariqrahiman@gmail.com

**Comment by anish-lakkapragada** [comment]
Were you able to successfully import ?

**Comment by anish-lakkapragada** [comment]
As for documentation, you can access it. It's all in the files (.py files) in the comments below classes and functions. Honestly the examples are probably much better, but if you want website documentation you can just use the pydoc module on any file. This will create an html file, and you may need to use an external library to make it run on localhost. I am currently working on using pydoc to make html files for each of my algorithms, then hosting them on a website.

**Comment by anish-lakkapragada** [comment]
Please let me know if you have any other issues with sealion at the moment with respect to the imports or code usage.

**Comment by anish-lakkapragada** [comment]
Also can you please give me a screenshot of your sealion folder? I want to see all the files and their names which will help me solve #5.

**Comment by tariqrahiman** [comment]
code run successfully

**Comment by anish-lakkapragada** [comment]
That's good! Also, can you give me the screenshot. This is will help me make sure other users don't have to go through this process. Thank you!

**Comment by tariqrahiman** [comment]
Lol, i cant find sealion folders inside C:\ProgramData\Anaconda3\Lib\site-packages after you had asked me to delete.
I installed through anaconda pip install sealion but i dont see the 2 folders now :-(

**Comment by anish-lakkapragada** [comment]
if you didn't have a sealion folder, how could the code run successfully? If you are able to use the sealion library, I think you should have its files somewhere. Please let me know if there was a misunderstanding,

**Comment by tariqrahiman** [comment]
Yes, i know. Till morning i could find the folder but after i deleted the 2 folders, I cant find it. See my install screen with new source 4.1
![success](https://user-images.githubusercontent.com/913554/107717864-72f65e00-6c89-11eb-9f37-78cd866e6146.png)

**Comment by anish-lakkapragada** [comment]
I rereleased to 4.1.3 to solve bug #5. You may want to just install that, without deleting anything. Then retry. I think this should work. Thank you for patience once again.

**Comment by tariqrahiman** [comment]
Should I un install and install ?

**Comment by anish-lakkapragada** [comment]
yes

**Comment by anish-lakkapragada** [comment]
make sure you are on 4.1.3

**Comment by anish-lakkapragada** [comment]
don't delete anything, you won't have to - just reinstall

**Comment by anish-lakkapragada** [comment]
with pip or pip3 install sealion==4.1.3

**Comment by tariqrahiman** [comment]
Weird this time the path changed to Python, when I installed 4.1 in the morning. That was the reason i couldnt find it
Previously it was under Ananconda. 
![uninstall-path](https://user-images.githubusercontent.com/913554/107718385-b30a1080-6c8a-11eb-9f80-02a67280c5d0.png)

**Comment by tariqrahiman** [comment]
Now I installed the latest and it is under **C:\ProgramData\Anaconda3\Lib\site-packages\**sealion-4.1.3.dist-info
screens below:
![4_1_3_a](https://user-images.githubusercontent.com/913554/107718906-cff31380-6c8b-11eb-9d26-abfb828809c2.png)
![4_1_3_b](https://user-images.githubusercontent.com/913554/107718914-d2ee0400-6c8b-11eb-80f2-c1a4443a158e.png)

**Comment by anish-lakkapragada** [comment]
It appears as though you have not ran "import sealion". That will generate the cython files. See what happens if you do that, and let me know if everything runs smoothly! thanks

**Comment by tariqrahiman** [comment]
What is the command to run?
Do you have it documented. I dont see it. I did pip install as you had recommended

**Comment by anish-lakkapragada** [comment]
I'm a bit confused - command to run what?

**Comment by tariqrahiman** [comment]
You said "It appears as though you have not ran "import sealion". That will generate the cython files. See what happens if you do that"
I am not sure where to run this import sealion command

**Comment by anish-lakkapragada** [comment]
Ohh, sorry about that. You need to run that in the shell that accesses those files and other libraries. Just import it from python 3.8 like you have done in the past.

**Comment by anish-lakkapragada** [comment]
The best solution would just be to upgrade to 4.1.8, where I have tried to fix this problem. First delete existing sealion directories, reupdate to 4.1.8. I apologize for this taking so long.

**Comment by tariqrahiman** [comment]
Upgraded to 4.1.8. Thanks Anish

**Comment by anish-lakkapragada** [comment]
Okay, that's good to hear! If you have no more problems, please let me know if it's okay for me to close this issue.

**Comment by tariqrahiman** [comment]
Thanks Anish for working with me on this issue. I am now able to proceed.

~ Tariq Rahiman
tariqrahiman@gmail.com
